import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
      >
        {children}
        <Toaster
          position="bottom-right"
          expand
          toastOptions={{
            className:
              "font-poppins flex items-center gap-3 px-4 py-3 rounded-2xl border border-white/50 bg-[linear-gradient(180deg,rgba(255,255,255,0.94),rgba(247,251,251,0.90))] text-[#023030] backdrop-blur-2xl shadow-[0_12px_32px_rgba(2,48,48,0.12)]",
          }}
        />
      </body>
    </html>
  );
}
